# Generated by Django 4.0.5 on 2022-06-30 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaign', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MeasStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='to fill', max_length=100)),
                ('date', models.DateField(blank=True, null=True, verbose_name='date of measurement')),
                ('description', models.CharField(blank=True, max_length=400, null=True)),
                ('campaign', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.campaign')),
            ],
        ),
        migrations.CreateModel(
            name='River',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('river', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('IDOC', 'Intragravel Dissolved Oxygen Content'), ('kf', 'Hydraulic Conductivity'), ('FC', 'Freeze Core'), ('SP', 'Shovel Sample'), ('FP', 'Freeze Panel'), ('LS', 'Line Sampling'), ('V', 'FlowTracker')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ShovelSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation')),
            ],
        ),
        migrations.AddField(
            model_name='measstation',
            name='method',
            field=models.ManyToManyField(to='flussdata.technique'),
        ),
        migrations.AddField(
            model_name='measstation',
            name='river',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.river'),
        ),
        migrations.CreateModel(
            name='LineSampling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation')),
            ],
        ),
        migrations.CreateModel(
            name='Kf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('dp_position', models.IntegerField(blank=True, null=True)),
                ('sediment_depth_m', models.FloatField(null=True)),
                ('wl_m', models.FloatField(blank=True, null=True)),
                ('kf_ms', models.FloatField(blank=True, null=True)),
                ('slurp_rate_avg_mls', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(max_length=1000)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation')),
            ],
        ),
        migrations.CreateModel(
            name='IDOC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('dp_position', models.IntegerField(blank=True, null=True, verbose_name='DP Position [-]')),
                ('sediment_depth_m', models.FloatField(null=True, verbose_name='Sediment Depth [m]')),
                ('wl_m', models.FloatField(blank=True, null=True, verbose_name='Water Level [m]')),
                ('H_m', models.FloatField(blank=True, null=True, verbose_name='H [m]')),
                ('idoc_mgl', models.FloatField(blank=True, null=True, verbose_name='IDOC [mg/l]')),
                ('temp_c', models.FloatField(blank=True, null=True, verbose_name='Temperature [C°]')),
                ('idoc_sat', models.FloatField(blank=True, null=True, verbose_name='IDOS [%]')),
                ('comment', models.CharField(max_length=1000)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation', verbose_name='Measurement station')),
            ],
        ),
        migrations.CreateModel(
            name='FreezePanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation')),
            ],
        ),
        migrations.CreateModel(
            name='Freezecore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('sample_name', models.CharField(max_length=200)),
                ('site_name', models.CharField(max_length=150)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('porosity_sfm', models.FloatField(blank=True, null=True)),
                ('dm', models.FloatField(blank=True, null=True)),
                ('dg', models.FloatField(blank=True, null=True)),
                ('fi', models.FloatField(blank=True, null=True)),
                ('geom_std_grain', models.FloatField(blank=True, null=True)),
                ('d10', models.FloatField(blank=True, null=True)),
                ('d16', models.FloatField(blank=True, null=True)),
                ('d25', models.FloatField(blank=True, null=True)),
                ('d30', models.FloatField(blank=True, null=True)),
                ('d50', models.FloatField(blank=True, null=True)),
                ('d60', models.FloatField(blank=True, null=True)),
                ('d75', models.FloatField(blank=True, null=True)),
                ('d84', models.FloatField(blank=True, null=True)),
                ('d90', models.FloatField(blank=True, null=True)),
                ('cu', models.FloatField(blank=True, null=True)),
                ('cc', models.FloatField(blank=True, null=True)),
                ('fsf_le_2mm', models.FloatField(blank=True, null=True)),
                ('fsf_le_1mm', models.FloatField(blank=True, null=True)),
                ('fsf_le_0_5mm', models.FloatField(blank=True, null=True)),
                ('so', models.FloatField(blank=True, null=True)),
                ('wl_slurp_m', models.FloatField(blank=True, null=True)),
                ('wl_model_m', models.FloatField(blank=True, null=True)),
                ('n_wooster', models.FloatField(blank=True, null=True)),
                ('bed_slope', models.FloatField(blank=True, null=True)),
                ('comment', models.CharField(max_length=1000)),
                ('percent_finer_250mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_125mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_63mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_31_5mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_16mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_8mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_4mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_2mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_1mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_0_5mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_0_25mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_0_125mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_0_063mm', models.FloatField(blank=True, null=True)),
                ('percent_finer_0_031mm', models.FloatField(blank=True, null=True)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation', verbose_name='Measurement station')),
            ],
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_id', models.CharField(max_length=200)),
                ('lon', models.FloatField(blank=True, null=True)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('meas_station', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation')),
            ],
        ),
    ]
