# Generated by Django 4.0.5 on 2022-06-24 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezecore',
            name='meas_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation', verbose_name='Measurement Station'),
        ),
    ]
