# Generated by Django 4.0.5 on 2022-09-06 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfacesed',
            name='n_frings',
            field=models.FloatField(blank=True, null=True, verbose_name='Porosity (Frings et al., 2011) [-]'),
        ),
    ]
