# Generated by Django 4.0.5 on 2022-06-24 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idoc',
            name='H_m',
            field=models.FloatField(blank=True, null=True, verbose_name='H [m]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='dp_position',
            field=models.IntegerField(blank=True, null=True, verbose_name='DP Position [-]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='idoc_mgl',
            field=models.FloatField(blank=True, null=True, verbose_name='IDOC [mg/l]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='idoc_sat',
            field=models.FloatField(blank=True, null=True, verbose_name='IDOS [%]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='meas_station',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='flussdata.measstation', verbose_name='Measurement station'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='sediment_depth_m',
            field=models.FloatField(null=True, verbose_name='Sediment Depth [m]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='temp_c',
            field=models.FloatField(blank=True, null=True, verbose_name='Temperature [C°]'),
        ),
        migrations.AlterField(
            model_name='idoc',
            name='wl_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Water Level [m]'),
        ),
    ]
