# Generated by Django 4.0.5 on 2022-06-09 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0002_alter_freezecore_d30'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezecore',
            name='bed_slope',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='n_wooster',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='wl_model_m',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='wl_slurp_m',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
