# Generated by Django 4.0.5 on 2022-09-06 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0002_surfacesed_n_frings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measstation',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date of measurement'),
        ),
    ]
