# Generated by Django 4.0.5 on 2022-06-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0003_alter_freezecore_bed_slope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_0_031mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_0_063mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_0_125mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_0_25mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_0_5mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_125mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_16mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_1mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_250mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_2mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_31_5mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_4mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_63mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='percent_finer_8mm',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
