# Generated by Django 4.0.5 on 2022-09-07 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0003_alter_measstation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kf',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
