# Generated by Django 4.0.5 on 2022-06-09 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0004_alter_freezecore_percent_finer_0_031mm_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='freezecore',
            name='cc',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='cu',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d10',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d16',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d25',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d50',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d60',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d75',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d84',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='d90',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='dg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='dm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='fi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='fsf_le_0_5mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='fsf_le_1mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='fsf_le_2mm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='geom_std_grain',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='porosity_sfm',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='freezecore',
            name='so',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
