# Generated by Django 4.0.5 on 2022-09-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flussdata', '0004_alter_kf_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsurfacesed',
            name='porosity_sfm',
        ),
    ]
