# Generated by Django 4.0.5 on 2022-09-07 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0005_remove_subsurfacesed_porosity_sfm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
