# Generated by Django 4.0.5 on 2022-09-08 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0007_alter_measstation_coord_system_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ido',
            name='dp_position',
            field=models.IntegerField(help_text='Double Packer Position. Mandatory field. Use intengers only.', null=True, verbose_name='DP Position [-]'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='meas_station',
            field=models.ForeignKey(help_text='This field will be used to link the parametrical data tablesto a given measurement point.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation', verbose_name='Measurement station'),
        ),
        migrations.AlterField(
            model_name='ido',
            name='sample_id',
            field=models.CharField(help_text='This field is used to differentiate between duplicate measurements performed in the same station. Thus, use thesame sample_id when it is intended to linkboth IDO and kf profiles to one specific measurementrepetition.', max_length=200),
        ),
        migrations.AlterField(
            model_name='kf',
            name='dp_position',
            field=models.IntegerField(default=int, help_text='Double Packer Position. Mandatory field. Use intengers only.', null=True, verbose_name='DP Position [-]'),
        ),
        migrations.AlterField(
            model_name='kf',
            name='meas_station',
            field=models.ForeignKey(help_text='This field will be used to link the parametrical data tablesto a given measurement point.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation'),
        ),
        migrations.AlterField(
            model_name='kf',
            name='sample_id',
            field=models.CharField(help_text='This field is used to differentiate between duplicate measurements performed in the same station. Thus, use thesame sample_id when it is intended to linkboth IDO and kf profiles to one specific measurementrepetition.', max_length=200),
        ),
        migrations.AlterField(
            model_name='measstation',
            name='date',
            field=models.DateField(blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.', null=True, verbose_name='Date of measurement'),
        ),
        migrations.AlterField(
            model_name='subsurfacesed',
            name='meas_station',
            field=models.ForeignKey(help_text='This field will be used to link the parametrical data tablesto a given measurement point.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation', verbose_name='Measurement station'),
        ),
        migrations.AlterField(
            model_name='subsurfacesed',
            name='sample_id',
            field=models.CharField(help_text='This field is used to differentiate between duplicate measurements performed in the same station.', max_length=200),
        ),
        migrations.AlterField(
            model_name='surfacesed',
            name='meas_station',
            field=models.ForeignKey(help_text='This field will be used to link the parametrical data tablesto a given measurement point.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation', verbose_name='Measurement station'),
        ),
    ]
