# Generated by Django 4.0.5 on 2022-09-09 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0009_alter_sedsampltechnique_samp_techniques'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measstation',
            name='coord_system',
            field=models.CharField(blank=True, help_text='The coordinate system is mandatory, please enter it as epsg number (eg., epsg:<epsg-code>).', max_length=15, null=True),
        ),
    ]
