# Generated by Django 4.0.5 on 2022-09-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0010_alter_measstation_coord_system'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsurfacesed',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='surfacesed',
            name='comment',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
