# Generated by Django 4.0.5 on 2022-09-16 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0011_alter_subsurfacesed_comment_alter_surfacesed_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='measstation',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.AddField(
            model_name='measstation',
            name='survey',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.survey'),
        ),
    ]
