# Generated by Django 4.0.5 on 2023-04-06 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0013_morphfeatures_morphunits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='biota',
            name='count_fish_redds',
            field=models.IntegerField(blank=True, null=True, verbose_name='Fish redds count'),
        ),
    ]
