# Generated by Django 4.0.5 on 2023-04-06 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0014_biota_count_fish_redds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biota',
            name='meas_station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation'),
        ),
        migrations.AlterField(
            model_name='waterqual',
            name='meas_station',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='riveranalyst.measstation'),
        ),
    ]
