# Generated by Django 3.2.18 on 2023-06-14 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0016_alter_morphology_meas_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='biota',
            name='count_fish_redds',
        ),
        migrations.RemoveField(
            model_name='biota',
            name='count_macrozoobenthos',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='morphological_features',
        ),
        migrations.RemoveField(
            model_name='morphology',
            name='morphological_unit',
        ),
        migrations.AddField(
            model_name='biota',
            name='fish_count',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Fish count'),
        ),
        migrations.AddField(
            model_name='biota',
            name='fish_redd_count',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Fish redds count'),
        ),
        migrations.AddField(
            model_name='biota',
            name='fish_species',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='biota',
            name='macrozoobenthos_count',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='Macrozoobenthos count'),
        ),
        migrations.AddField(
            model_name='biota',
            name='macrozoobenthos_species',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='morphology',
            name='morph_features',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='morphology',
            name='morph_unit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.DeleteModel(
            name='MorphFeatures',
        ),
        migrations.DeleteModel(
            name='MorphUnits',
        ),
    ]
