# Generated by Django 3.2.18 on 2023-06-26 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0018_auto_20230619_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hydraulics',
            name='kt',
            field=models.FloatField(blank=True, null=True, verbose_name='kt [m^2/s^2]'),
        ),
        migrations.AlterField(
            model_name='hydraulics',
            name='kt_2d',
            field=models.FloatField(blank=True, null=True, verbose_name='kt 2d [m^2/s^2]'),
        ),
    ]
