# Generated by Django 3.2.18 on 2023-07-20 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riveranalyst', '0019_auto_20230626_0945'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measposition',
            name='wl_m',
        ),
        migrations.RemoveField(
            model_name='measposition',
            name='wl_model_m',
        ),
        migrations.AddField(
            model_name='measposition',
            name='wd_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Water depth measured in situ [m]'),
        ),
        migrations.AddField(
            model_name='measposition',
            name='wd_model_m',
            field=models.FloatField(blank=True, null=True, verbose_name='Modelled water depth [m]'),
        ),
    ]
