from django.db import models
from django.core.validators import MaxValueValidator, MinValueValidator
from django.utils import timezone


class Freezecore(models.Model):
    river = models.CharField(max_length=100)
    sample_id = models.CharField(max_length=200)
    sample_name = models.CharField(max_length=200)
    site_name = models.CharField(max_length=150)
    date = models.DateField('date of measurement')
    time_stamp = models.CharField(max_length=150)
    lon = models.FloatField()
    lat = models.FloatField()
    porosity_sfm = models.FloatField()
    dm = models.FloatField()
    dg = models.FloatField()
    fi = models.FloatField()
    geom_std_grain = models.FloatField()
    d10 = models.FloatField()
    d16 = models.FloatField()
    d25 = models.FloatField()
    d30 = models.FloatField()
    d50 = models.FloatField()
    d60 = models.FloatField()
    d75 = models.FloatField()
    d84 = models.FloatField()
    d90 = models.FloatField()
    cu = models.FloatField()
    cc = models.FloatField()
    fsf_le_2mm = models.FloatField()
    fsf_le_1mm = models.FloatField()
    fsf_le_0_5mm = models.FloatField()
    so = models.FloatField()
    wl_slurp_m = models.FloatField()
    wl_model_m = models.FloatField()
    n_wooster = models.FloatField()
    bed_slope = models.FloatField()
    comment = models.CharField(max_length=1000)
    percent_finer_250mm = models.FloatField()
    percent_finer_125mm = models.FloatField()
    percent_finer_63mm = models.FloatField()
    percent_finer_31_5mm = models.FloatField()
    percent_finer_16mm = models.FloatField()
    percent_finer_8mm = models.FloatField()
    percent_finer_4mm = models.FloatField()
    percent_finer_2mm = models.FloatField()
    percent_finer_1mm = models.FloatField()
    percent_finer_0_5mm = models.FloatField()
    percent_finer_0_25mm = models.FloatField()
    percent_finer_0_125mm = models.FloatField()
    percent_finer_0_063mm = models.FloatField()
    percent_finer_0_031mm = models.FloatField()